/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Logica.*;
import java.util.HashMap;
import javax.swing.table.TableModel;

/**
 *
 * @author Cristopher Matus
 */
public class Mundial extends javax.swing.JFrame {

    /**
     * Creates new form Mundial
     */
    public Mundial() {
        initComponents();
        cargarDatos();
        setLocationRelativeTo(null);
        setResizable(false);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        teamMatches = new HashMap<>();
    }
    private HashMap<String, Integer> teamMatches;
    private CAF CAF;
    private OFC OFC;
    private CONMEBOL CONMEBOL;
    private Concacaf Concacaf;
    private UEFA UEFA;
    
    /**
     * @return the CAF
     */
    public CAF getCAF() {
        if (this.CAF == null) {
            this.CAF = new CAF();
        }
        return CAF;
    }

    /**
     * @param CAF the CAF to set
     */
    public void setCAF(CAF CAF) {
        this.CAF = CAF;
    }

     /**
     * @return the OFC
     */
    public OFC getOFC() {
        if (this.OFC == null) {
            this.OFC = new OFC();
        }
        return OFC;
    }

    /**
     * @param OFC the OFC to set
     */
    public void setOFC(OFC OFC) {
        this.OFC = OFC;
    }

    /**
     * @return the CONMEBOL
     */
    public CONMEBOL getCONMEBOL() {
        if (this.CONMEBOL == null) {
            this.CONMEBOL = new CONMEBOL();
        }
        return CONMEBOL;
    }

    /**
     * @param CONMEBOL the CONMEBOL to set
     */
    public void setCONMEBOL(CONMEBOL CONMEBOL) {
        this.CONMEBOL = CONMEBOL;
    }

    /**
     * @return the Concacaf
     */
    public Concacaf getConcacaf() {
        if (this.Concacaf == null) {
            this.Concacaf = new Concacaf();
        }
        return Concacaf;
    }

    /**
     * @param Concacaf the Concacaf to set
     */
    public void setConcacaf(Concacaf Concacaf) {
        this.Concacaf = Concacaf;
    }

    /**
     * @return the UEFA
     */
    public UEFA getUEFA() {
        if (this.UEFA == null) {
            this.UEFA = new UEFA();
        }
        return UEFA;
    }

    /**
     * @param UEFA the UEFA to set
     */
    public void setUEFA(UEFA UEFA) {
        this.UEFA = UEFA;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        tbpCAF = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCAF = new javax.swing.JTable();
        btnSimularCAF = new javax.swing.JButton();
        btnSimularTodoCAF = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtSimuladosCAF = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConcacaf = new javax.swing.JTable();
        btnSimularConca = new javax.swing.JButton();
        btnSimularTodoConca = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtSimuladosConca = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCONMEBOL = new javax.swing.JTable();
        btnSimularConme = new javax.swing.JButton();
        btnSimularTodoConme = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtSimuladosConme = new javax.swing.JTextArea();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblUEFA = new javax.swing.JTable();
        btnSimularUEFA = new javax.swing.JButton();
        btnSimularTodoUEFA = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtSimuladosUEFA = new javax.swing.JTextArea();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblOFC = new javax.swing.JTable();
        btnSimularOFC = new javax.swing.JButton();
        btnSimularTodos = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSimuladosOFC = new javax.swing.JTextArea();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblClasificados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbpCAF.setBackground(new java.awt.Color(153, 153, 255));
        tbpCAF.setForeground(new java.awt.Color(51, 51, 51));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 652, Short.MAX_VALUE)
        );

        tbpCAF.addTab("Inicio", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        tblCAF.setBackground(new java.awt.Color(102, 102, 102));
        tblCAF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblCAF.setForeground(new java.awt.Color(255, 255, 255));
        tblCAF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pos", "Seleccion", "PTS", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"
            }
        ));
        jScrollPane1.setViewportView(tblCAF);

        btnSimularCAF.setText("Simular");
        btnSimularCAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularCAFActionPerformed(evt);
            }
        });

        btnSimularTodoCAF.setText("Simular Todo");
        btnSimularTodoCAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularTodoCAFActionPerformed(evt);
            }
        });

        txtSimuladosCAF.setColumns(20);
        txtSimuladosCAF.setRows(5);
        jScrollPane7.setViewportView(txtSimuladosCAF);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimularTodoCAF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimularCAF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnSimularCAF)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimularTodoCAF))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tbpCAF.addTab("CAF", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        tblConcacaf.setBackground(new java.awt.Color(255, 255, 153));
        tblConcacaf.setBorder(new javax.swing.border.MatteBorder(null));
        tblConcacaf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pos", "Seleccion", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"
            }
        ));
        jScrollPane2.setViewportView(tblConcacaf);

        btnSimularConca.setText("Simular");
        btnSimularConca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularConcaActionPerformed(evt);
            }
        });

        btnSimularTodoConca.setText("Simular Todo");

        txtSimuladosConca.setColumns(20);
        txtSimuladosConca.setRows(5);
        jScrollPane8.setViewportView(txtSimuladosConca);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimularTodoConca)
                    .addComponent(btnSimularConca))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSimularConca)
                        .addGap(32, 32, 32)
                        .addComponent(btnSimularTodoConca))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tbpCAF.addTab("Concacaf", jPanel3);

        tblCONMEBOL.setBackground(new java.awt.Color(0, 102, 153));
        tblCONMEBOL.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tblCONMEBOL.setForeground(new java.awt.Color(255, 255, 153));
        tblCONMEBOL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pos", "Selección", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif."
            }
        ));
        jScrollPane3.setViewportView(tblCONMEBOL);

        btnSimularConme.setText("Simular");
        btnSimularConme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularConmeActionPerformed(evt);
            }
        });

        btnSimularTodoConme.setText("Simular Todo");

        txtSimuladosConme.setColumns(20);
        txtSimuladosConme.setRows(5);
        jScrollPane9.setViewportView(txtSimuladosConme);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimularConme)
                    .addComponent(btnSimularTodoConme))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnSimularConme)
                        .addGap(45, 45, 45)
                        .addComponent(btnSimularTodoConme)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tbpCAF.addTab("CONMEBOL", jPanel4);

        jTabbedPane3.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane3.setForeground(new java.awt.Color(0, 204, 204));

        tblUEFA.setBackground(new java.awt.Color(51, 51, 51));
        tblUEFA.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tblUEFA.setForeground(new java.awt.Color(255, 255, 255));
        tblUEFA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pos", "Selección", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif."
            }
        ));
        jScrollPane10.setViewportView(tblUEFA);

        btnSimularUEFA.setText("Simular");
        btnSimularUEFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularUEFAActionPerformed(evt);
            }
        });

        btnSimularTodoUEFA.setText("Simular Todo");

        txtSimuladosUEFA.setColumns(20);
        txtSimuladosUEFA.setRows(5);
        jScrollPane5.setViewportView(txtSimuladosUEFA);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimularTodoUEFA)
                    .addComponent(btnSimularUEFA))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(423, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btnSimularUEFA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimularTodoUEFA)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(218, Short.MAX_VALUE)))
        );

        jTabbedPane3.addTab("Europa", jPanel6);

        tbpCAF.addTab("UEFA", jTabbedPane3);

        jTabbedPane2.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTabbedPane2.setForeground(new java.awt.Color(102, 255, 102));

        tblOFC.setBackground(new java.awt.Color(204, 102, 0));
        tblOFC.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tblOFC.setForeground(new java.awt.Color(51, 204, 255));
        tblOFC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pos", "Selección", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"
            }
        ));
        jScrollPane11.setViewportView(tblOFC);

        btnSimularOFC.setText("Simular");
        btnSimularOFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularOFCActionPerformed(evt);
            }
        });

        btnSimularTodos.setText("Simular Todos");

        txtSimuladosOFC.setColumns(20);
        txtSimuladosOFC.setRows(5);
        jScrollPane4.setViewportView(txtSimuladosOFC);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimularTodos)
                    .addComponent(btnSimularOFC))
                .addGap(72, 72, 72)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimularOFC)
                .addGap(43, 43, 43)
                .addComponent(btnSimularTodos)
                .addGap(96, 96, 96))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(243, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Oceania", jPanel7);

        tbpCAF.addTab("OFC", jTabbedPane2);

        tblClasificados.setBackground(new java.awt.Color(0, 102, 102));
        tblClasificados.setForeground(new java.awt.Color(204, 204, 204));
        tblClasificados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pos", "Selección", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"
            }
        ));
        jScrollPane6.setViewportView(tblClasificados);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                .addGap(93, 93, 93))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 200, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Clasificados", jPanel5);

        tbpCAF.addTab("Clasificados", jTabbedPane5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpCAF, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpCAF, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//explicar aqui y no todo

    public void cargarDatos() {
        Pais pais = new Pais();
        //creo el modelo para cada tabla y jala los datos de la clase pais
        DefaultTableModel modeloConcacaf = new DefaultTableModel();
        this.tblConcacaf.setModel(modeloConcacaf);
        modeloConcacaf.setDataVector(pais.cargarPaisConcacaf(), new Object[]{"Selección", "Pos", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"});
        //creo el modelo para cada tabla y jala los datos de la clase pais
        DefaultTableModel modeloCAF = new DefaultTableModel();
        this.tblCAF.setModel(modeloCAF);
        modeloCAF.setDataVector(pais.cargarPaisCAF(), new Object[]{"Selección", "Pos", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"});
        //creo el modelo para cada tabla y jala los datos de la clase pais
        DefaultTableModel modeloCONMEBOL = new DefaultTableModel();
        this.tblCONMEBOL.setModel(modeloCONMEBOL);
        modeloCONMEBOL.setDataVector(pais.cargarPaisCONMEBOL(), new Object[]{"Selección", "Pos", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"});
        //creo el modelo para cada tabla y jala los datos de la clase pais
        DefaultTableModel modeloUEFA = new DefaultTableModel();
        this.tblUEFA.setModel(modeloUEFA);
        modeloUEFA.setDataVector(pais.cargarPaisUEFA(), new Object[]{"Selección", "Pos", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"});
        //creo el modelo para cada tabla y jala los datos de la clase pais
        DefaultTableModel modeloOFC = new DefaultTableModel();
        this.tblOFC.setModel(modeloOFC);
        modeloOFC.setDataVector(pais.cargarPaisOFC(), new Object[]{"Selección", "Pos", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"});
    }

    //this.tblClasificados.setModel(modelo);

    private void btnSimularCAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularCAFActionPerformed
        // Obtener el número de filas y columnas del modelo de datos

        int filas = tblCAF.getRowCount();
        ArrayList<Selecion> seleciones = new ArrayList<>();
        for (int i = 0; i < filas; i++) {
            Selecion caf = new Selecion(
                    (String) tblCAF.getValueAt(i, 0),
                    (int) tblCAF.getValueAt(i, 1),
                    (int) tblCAF.getValueAt(i, 2),
                    (int) tblCAF.getValueAt(i, 3),
                    (int) tblCAF.getValueAt(i, 4),
                    (int) tblCAF.getValueAt(i, 5),
                    (int) tblCAF.getValueAt(i, 6),
                    (int) tblCAF.getValueAt(i, 7),
                    (int) tblCAF.getValueAt(i, 8),
                    (int) tblCAF.getValueAt(i, 9)
            );
            seleciones.add(caf);
        }
        this.getCAF().settablaCaf(seleciones);
        this.getCAF().jugarPartido();
        List<Resultados> tablaPartido = this.getCAF().getTablaPartido();
        if (!tablaPartido.isEmpty()) {
        Resultados res = this.getCAF().getTablaPartido().get(this.getCAF().getTablaPartido().size() - 1);
        // Actualizar la interfaz gráfica con los resultados obtenidos.
        this.txtSimuladosCAF.setText(this.Imprimir(res));
        this.ActualizarTabla(this.getCAF().gettablaCaf(), this.tblCAF);
    }
//<<<<<<< HEAD
        this.ActualizarTabla(this.getCAF().gettablaCaf(), this.tblCAF);
        
//=======
        this.ActualizarTabla(this.getCAF().gettablaCaf(), this.tblCAF);


//>>>>>>> main
    }//GEN-LAST:event_btnSimularCAFActionPerformed

    private void ActualizarTabla(ArrayList<Selecion> seleciones, JTable table) {
        // Crear el modelo de tabla
        DefaultTableModel modelo = new DefaultTableModel();

        Object[][] Seleciones = new Object[10][10];
        int position = 0;
        for (Selecion sele : seleciones) {
            Object[] fila = {sele.getSelecion(), sele.getPos(), sele.getPuntos(), sele.getPartidosJugados(),
                sele.getPartidosGanados(), sele.getPartidosEmpatados(), sele.getPartidosPerdidos(),
                sele.getGolesFavor(), sele.getGolesContra(), sele.getDiferenciaGoles()};
            Seleciones[position] = fila;
            position++;
        }

        table.setModel(modelo);
        modelo.setDataVector(Seleciones, new Object[]{"Selección", "Pos", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"});
    }

    private String Imprimir(Resultados res) {
        return "El resultado del juego entre " + res.getSelecion1() + " vs " + res.getSelecion2() + " es de " + res.getPos() + " - " + res.getPuntos();
    }

    private void btnSimularOFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularOFCActionPerformed
        // Obtener el número de filas y columnas del modelo de datos
        int filas = tblOFC.getRowCount();
        ArrayList<Selecion> seleciones = new ArrayList<>();
        for (int i = 0; i < filas; i++) {
            Selecion ofc = new Selecion(
                    (String) tblOFC.getValueAt(i, 0),
                    (int) tblOFC.getValueAt(i, 1),
                    (int) tblOFC.getValueAt(i, 2),
                    (int) tblOFC.getValueAt(i, 3),
                    (int) tblOFC.getValueAt(i, 4),
                    (int) tblOFC.getValueAt(i, 5),
                    (int) tblOFC.getValueAt(i, 6),
                    (int) tblOFC.getValueAt(i, 7),
                    (int) tblOFC.getValueAt(i, 8),
                    (int) tblOFC.getValueAt(i, 9)
            );
            seleciones.add(ofc);
        }

        this.getOFC().setTablaOFC(seleciones);
        this.getOFC().jugarPartido();
        Resultados res = this.getOFC().getTablaPartido().get(this.getOFC().getTablaPartido().size() - 1);
        this.txtSimuladosOFC.setText(this.Imprimir(res));
        this.ActualizarTabla(this.getOFC().getTablaOFC(), this.tblOFC);

    }//GEN-LAST:event_btnSimularOFCActionPerformed

    private void btnSimularConcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularConcaActionPerformed
        // Obtener el número de filas y columnas del modelo de datos
        int filas = tblConcacaf.getRowCount();
        ArrayList<Selecion> seleciones = new ArrayList<>();
        for (int i = 0; i < filas; i++) {
            Selecion conca = new Selecion(
                    (String) tblConcacaf.getValueAt(i, 0),
                    (int) tblConcacaf.getValueAt(i, 1),
                    (int) tblConcacaf.getValueAt(i, 2),
                    (int) tblConcacaf.getValueAt(i, 3),
                    (int) tblConcacaf.getValueAt(i, 4),
                    (int) tblConcacaf.getValueAt(i, 5),
                    (int) tblConcacaf.getValueAt(i, 6),
                    (int) tblConcacaf.getValueAt(i, 7),
                    (int) tblConcacaf.getValueAt(i, 8),
                    (int) tblConcacaf.getValueAt(i, 9)
            );
            seleciones.add(conca);
        }

        this.getConcacaf().setTablaConcacaf(seleciones);
        this.getConcacaf().jugarPartido();
        Resultados res = this.getConcacaf().getTablaPartido().get(this.getConcacaf().getTablaPartido().size() - 1);
        this.txtSimuladosConca.setText(this.Imprimir(res));
        this.ActualizarTabla(this.getConcacaf().getTablaConcacaf(), this.tblConcacaf);


    }//GEN-LAST:event_btnSimularConcaActionPerformed

    private void btnSimularConmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularConmeActionPerformed
        // Obtener el número de filas y columnas del modelo de datos
        int filas = tblCONMEBOL.getRowCount();
        ArrayList<Selecion> seleciones = new ArrayList<>();
        for (int i = 0; i < filas; i++) {
            Selecion conme = new Selecion(
                    (String) tblCONMEBOL.getValueAt(i, 0),
                    (int) tblCONMEBOL.getValueAt(i, 1),
                    (int) tblCONMEBOL.getValueAt(i, 2),
                    (int) tblCONMEBOL.getValueAt(i, 3),
                    (int) tblCONMEBOL.getValueAt(i, 4),
                    (int) tblCONMEBOL.getValueAt(i, 5),
                    (int) tblCONMEBOL.getValueAt(i, 6),
                    (int) tblCONMEBOL.getValueAt(i, 7),
                    (int) tblCONMEBOL.getValueAt(i, 8),
                    (int) tblCONMEBOL.getValueAt(i, 9)
            );
            seleciones.add(conme);
        }

        this.getCONMEBOL().setTablaCONMEBOL(seleciones);
        this.getCONMEBOL().jugarPartido();
        Resultados res = this.getCONMEBOL().getTablaPartido().get(this.getCONMEBOL().getTablaPartido().size() - 1);
        this.txtSimuladosConme.setText(this.Imprimir(res));
        this.ActualizarTabla(this.getCONMEBOL().getTablaCONMEBOL(), this.tblCONMEBOL);

    }//GEN-LAST:event_btnSimularConmeActionPerformed

    private void btnSimularUEFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularUEFAActionPerformed
        // Obtener el número de filas y columnas del modelo de datos

        int filas = tblUEFA.getRowCount();
        ArrayList<Selecion> seleciones = new ArrayList<>();
        for (int i = 0; i < filas; i++) {
            Selecion uefa = new Selecion(
                    (String) tblUEFA.getValueAt(i, 0),
                    (int) tblUEFA.getValueAt(i, 1),
                    (int) tblUEFA.getValueAt(i, 2),
                    (int) tblUEFA.getValueAt(i, 3),
                    (int) tblUEFA.getValueAt(i, 4),
                    (int) tblUEFA.getValueAt(i, 5),
                    (int) tblUEFA.getValueAt(i, 6),
                    (int) tblUEFA.getValueAt(i, 7),
                    (int) tblUEFA.getValueAt(i, 8),
                    (int) tblUEFA.getValueAt(i, 9)
            );
            seleciones.add(uefa);
        }
        this.getUEFA().setTablaUEFA(seleciones);
        this.getUEFA().jugarPartido();
        Resultados res = this.getUEFA().getTablaPartidoUEFA().get(this.getUEFA().getTablaPartidoUEFA().size() - 1);
        this.txtSimuladosUEFA.setText(this.Imprimir(res));
        this.ActualizarTabla(this.getUEFA().getTablaUEFA(), this.tblUEFA);


    }

    /**
     * @param evt
     */
    private void btnSimularTodoCAFActionPerformed(java.awt.event.ActionEvent evt) {
        HashMap<String, Integer> teamMatches = new HashMap<>();
    
        int rowCount = tblCAF.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            String team1Str = (String) tblCAF.getValueAt(i, 0);
            String team2Str = (String) tblCAF.getValueAt(i, 1);
            int team1 = Integer.parseInt(team1Str);
            int team2 = Integer.parseInt(team2Str);
    
            String teamPair = team1 + "-" + team2;
            if (teamMatches.containsKey(teamPair)) {
                int matchesPlayed = teamMatches.get(teamPair);
                teamMatches.put(teamPair, matchesPlayed + 1);
            } else {
                teamMatches.put(teamPair, 1);
            }
        }
    
        for (String teamPair : teamMatches.keySet()) {
            String[] teams = teamPair.split("-");
            int matchesToPlay = 2 - teamMatches.get(teamPair);
            for (int i = 0; i < matchesToPlay; i++) {
                int team1 = Integer.parseInt(teams[0]);
                int team2 = Integer.parseInt(teams[1]);
                this.getCAF().simularYActualizarPartido(team1, team2);
            }
        }
    
        // Actualizar la interfaz gráfica con los resultados obtenidos.
        List<Resultados> tablaPartido = this.getCAF().getTablaPartido();
        if (!tablaPartido.isEmpty()) {
            Resultados res = tablaPartido.get(tablaPartido.size() - 1);
            this.txtSimuladosCAF.setText(this.Imprimir(res));
            this.ActualizarTabla(this.getCAF().gettablaCaf(), this.tblCAF);
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimularCAF;
    private javax.swing.JButton btnSimularConca;
    private javax.swing.JButton btnSimularConme;
    private javax.swing.JButton btnSimularOFC;
    private javax.swing.JButton btnSimularTodoCAF;
    private javax.swing.JButton btnSimularTodoConca;
    private javax.swing.JButton btnSimularTodoConme;
    private javax.swing.JButton btnSimularTodoUEFA;
    private javax.swing.JButton btnSimularTodos;
    private javax.swing.JButton btnSimularUEFA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable tblCAF;
    private javax.swing.JTable tblCONMEBOL;
    private javax.swing.JTable tblClasificados;
    private javax.swing.JTable tblConcacaf;
    private javax.swing.JTable tblOFC;
    private javax.swing.JTable tblUEFA;
    private javax.swing.JTabbedPane tbpCAF;
    private javax.swing.JTextArea txtSimuladosCAF;
    private javax.swing.JTextArea txtSimuladosConca;
    private javax.swing.JTextArea txtSimuladosConme;
    private javax.swing.JTextArea txtSimuladosOFC;
    private javax.swing.JTextArea txtSimuladosUEFA;
    // End of variables declaration//GEN-END:variables

   

}
